/** This file was Autogenerated */

import { GroupCreatedEventSchema } from './Events/GroupCreatedEvent';
import { GroupDeletedEventSchema } from './Events/GroupDeletedEvent';
import { GroupUpdatedEventSchema } from './Events/GroupUpdatedEvent';
import { IlpIdentifiedEventSchema } from './Events/IlpIdentifiedEvent';
import { IlpRetrievedEventSchema } from './Events/IlpRetrievedEvent';
import { LessonCompletedEventSchema } from './Events/LessonCompletedEvent';
import { LessonGradedEventSchema } from './Events/LessonGradedEvent';
import { LessonResetEventSchema } from './Events/LessonResetEvent';
import { LessonSkippedEventSchema } from './Events/LessonSkippedEvent';
import { LessonStartedEventSchema } from './Events/LessonStartedEvent';
import { LoginFailedEventSchema } from './Events/LoginFailedEvent';
import { LoginSuccessEventSchema } from './Events/LoginSuccessEvent';
import { LogoutEventSchema } from './Events/LogoutEvent';
import { MembershipCreatedEventSchema } from './Events/MembershipCreatedEvent';
import { MembershipDeletedEventSchema } from './Events/MembershipDeletedEvent';
import { NavigationEventSchema } from './Events/NavigationEvent';
import { OrganizationActivatedEventSchema } from './Events/OrganizationActivatedEvent';
import { OrganizationCreatedEventSchema } from './Events/OrganizationCreatedEvent';
import { OrganizationDeactivatedEventSchema } from './Events/OrganizationDeactivatedEvent';
import { OrganizationDeletedEventSchema } from './Events/OrganizationDeletedEvent';
import { OrganizationUpdatedEventSchema } from './Events/OrganizationUpdatedEvent';
import { UserActivatedEventSchema } from './Events/UserActivatedEvent';
import { UserCreatedEventSchema } from './Events/UserCreatedEvent';
import { UserDeactivatedEventSchema } from './Events/UserDeactivatedEvent';
import { UserDeletedEventSchema } from './Events/UserDeletedEvent';
import { UserUpdatedEventSchema } from './Events/UserUpdatedEvent';

export const schemas = {
	[GroupCreatedEventSchema.context]: GroupCreatedEventSchema.schema,
	[GroupUpdatedEventSchema.context]: GroupUpdatedEventSchema.schema,
	[GroupDeletedEventSchema.context]: GroupDeletedEventSchema.schema,
	[IlpIdentifiedEventSchema.context]: IlpIdentifiedEventSchema.schema,
	[IlpRetrievedEventSchema.context]: IlpRetrievedEventSchema.schema,
	[LessonStartedEventSchema.context]: LessonStartedEventSchema.schema,
	[LessonCompletedEventSchema.context]: LessonCompletedEventSchema.schema,
	[LessonSkippedEventSchema.context]: LessonSkippedEventSchema.schema,
	[LessonResetEventSchema.context]: LessonResetEventSchema.schema,
	[LessonGradedEventSchema.context]: LessonGradedEventSchema.schema,
	[LogoutEventSchema.context]: LogoutEventSchema.schema,
	[LoginSuccessEventSchema.context]: LoginSuccessEventSchema.schema,
	[LoginFailedEventSchema.context]: LoginFailedEventSchema.schema,
	[MembershipCreatedEventSchema.context]: MembershipCreatedEventSchema.schema,
	[MembershipDeletedEventSchema.context]: MembershipDeletedEventSchema.schema,
	[NavigationEventSchema.context]: NavigationEventSchema.schema,
	[OrganizationCreatedEventSchema.context]: OrganizationCreatedEventSchema.schema,
	[OrganizationUpdatedEventSchema.context]: OrganizationUpdatedEventSchema.schema,
	[OrganizationDeletedEventSchema.context]: OrganizationDeletedEventSchema.schema,
	[OrganizationActivatedEventSchema.context]: OrganizationActivatedEventSchema.schema,
	[OrganizationDeactivatedEventSchema.context]: OrganizationDeactivatedEventSchema.schema,
	[UserCreatedEventSchema.context]: UserCreatedEventSchema.schema,
	[UserUpdatedEventSchema.context]: UserUpdatedEventSchema.schema,
	[UserDeletedEventSchema.context]: UserDeletedEventSchema.schema,
	[UserActivatedEventSchema.context]: UserActivatedEventSchema.schema,
	[UserDeactivatedEventSchema.context]: UserDeactivatedEventSchema.schema,
};
