/** This file was Autogenerated */
export enum CaliperProfile {
	GeneralProfile = 'GeneralProfile',
	AnnotationProfile = 'AnnotationProfile',
	AssessmentProfile = 'AssessmentProfile',
	AssignableProfile = 'AssignableProfile',
	FeedbackProfile = 'FeedbackProfile',
	ForumProfile = 'ForumProfile',
	GradingProfile = 'GradingProfile',
	MediaProfile = 'MediaProfile',
	ReadingProfile = 'ReadingProfile',
	ResourceManagementProfile = 'ResourceManagementProfile',
	SearchProfile = 'SearchProfile',
	SessionProfile = 'SessionProfile',
	ToolLaunchProfile = 'ToolLaunchProfile',
	ToolUseProfile = 'ToolUseProfile',
}
