/** This file was Autogenerated */

import Caliper from './../Caliper';
import { IAgent } from './../Entities/Agent';
import { IClass } from './../Entities/Class';
import { IEntity } from './../Entities/Entity';
import { IGroup } from './../Entities/Group';
import { IInstructor } from './../Entities/Instructor';
import { ILtiSession } from './../Entities/LtiSession';
import { IMembership } from './../Entities/Membership';
import { IOrganization } from './../Entities/Organization';
import { ISession } from './../Entities/Session';
import { ISoftwareApplication } from './../Entities/SoftwareApplication';
import { IStudent } from './../Entities/Student';
import { IUser } from './../Entities/User';
import { CaliperAction } from './CaliperAction';
import { CaliperProfile } from './CaliperProfile';
import { IEvent } from './Event';
import { EventType } from './EventType';

export interface IGroupDeletedEvent extends IEvent {
	actor: ISoftwareApplication | IUser | IInstructor | IStudent;
	object: IGroup | IClass;
}

interface IGroupDeletedEventParams {
	actor: ISoftwareApplication | IUser | IInstructor | IStudent;
	object: IGroup | IClass;
	profile?: CaliperProfile;
	target?: IEntity;
	generated?: IEntity;
	group?: IOrganization;
	membership?: IMembership;
	federatedSession?: ILtiSession;
	session?: ISession;
	referrer?: IEntity;
	extensions?: Record<string, any>;
}

export function GroupDeletedEvent(params: IGroupDeletedEventParams): IGroupDeletedEvent {
	return {
		['@context']: ['http://edgenuity.com/events/group-deleted/0-0-2', 'http://purl.imsglobal.org/ctx/caliper/v1p2'],
		type: EventType.GroupEvent,
		action: CaliperAction.Deleted,
		id: Caliper.uuid(),
		eventTime: Caliper.timestamp(),
		edApp: Caliper.edApp(),
		...params
	};
}

export const GroupDeletedEventSchema = {
	context: 'http://edgenuity.com/events/group-deleted/0-0-2',
	schema: {
		title: 'GroupDeletedEvent',
		type: 'object',
		required: ['@context', 'type', 'action', 'actor', 'object', 'id', 'eventTime', 'edApp'],
		properties: {
			'@context': {
				type: 'array',
				items: [
					{
						type: 'string',
						default: 'http://edgenuity.com/events/group-deleted/0-0-2',
						enum: ['http://edgenuity.com/events/group-deleted/0-0-2']
					},
					{
						type: 'string',
						default: 'http://purl.imsglobal.org/ctx/caliper/v1p2',
						enum: ['http://purl.imsglobal.org/ctx/caliper/v1p2']
					}
				]
			},
			type: {
				type: 'string',
				default: 'GroupEvent',
				enum: ['GroupEvent']
			},
			action: {
				type: 'string',
				default: 'Deleted',
				enum: ['Deleted']
			},
			actor: {
				required: ['id', 'type'],
				oneOf: [
					{
						title: 'SoftwareApplication',
						$ref: '#/definitions/SoftwareApplication'
					},
					{
						title: 'User',
						$ref: '#/definitions/User'
					},
					{
						title: 'Instructor',
						$ref: '#/definitions/Instructor'
					},
					{
						title: 'Student',
						$ref: '#/definitions/Student'
					}
				]
			},
			object: {
				required: ['id', 'type'],
				oneOf: [
					{
						title: 'Group',
						$ref: '#/definitions/Group'
					},
					{
						title: 'Class',
						$ref: '#/definitions/Class'
					}
				]
			},
			id: {
				type: 'string',
				pattern: 'urn\\:uuid\\:\\w{8}-\\w{4}-\\w{4}-\\w{4}-\\w{12}'
			},
			eventTime: {
				type: 'string',
				format: 'date-time'
			},
			edApp: {
				title: 'SoftwareApplication',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'SoftwareApplication',
						$ref: '#/definitions/SoftwareApplication'
					}
				]
			},
			profile: {
				title: 'CaliperProfile',
				$ref: '#/definitions/CaliperProfile'
			},
			target: {
				title: 'Entity',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'Entity',
						$ref: '#/definitions/Entity'
					}
				]
			},
			generated: {
				title: 'Entity',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'Entity',
						$ref: '#/definitions/Entity'
					}
				]
			},
			group: {
				title: 'Organization',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'Organization',
						$ref: '#/definitions/Organization'
					}
				]
			},
			membership: {
				title: 'Membership',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'Membership',
						$ref: '#/definitions/Membership'
					}
				]
			},
			federatedSession: {
				title: 'LtiSession',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'LtiSession',
						$ref: '#/definitions/LtiSession'
					}
				]
			},
			session: {
				title: 'Session',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'Session',
						$ref: '#/definitions/Session'
					}
				]
			},
			referrer: {
				title: 'Entity',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'Entity',
						$ref: '#/definitions/Entity'
					}
				]
			},
			extensions: {
				type: 'object',
				additionalProperties: true
			}
		},
		definitions: {
			SoftwareApplication: {
				title: 'SoftwareApplication',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'SoftwareApplication',
						enum: ['SoftwareApplication']
					},
					version: {
						type: 'string'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Uri: {
				type: 'string',
				oneOf: [
					{
						pattern: '^https?:\\/\\/\\w.+\\.\\w+[/\\w+]*'
					},
					{
						pattern: 'urn\\:.*'
					}
				]
			},
			SystemIdentifier: {
				title: 'SystemIdentifier',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'SystemIdentifier',
						enum: ['SystemIdentifier']
					},
					identifierType: {
						title: 'SystemIdentifierType',
						$ref: '#/definitions/SystemIdentifierType'
					},
					identifier: {
						type: 'string'
					},
					source: {
						title: 'SoftwareApplication',
						allOf: [
							{
								required: ['type', 'id']
							},
							{
								title: 'SoftwareApplication',
								$ref: '#/definitions/SoftwareApplication'
							}
						]
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			SystemIdentifierType: {
				type: 'string',
				title: 'SystemIdentifierType',
				enum: [
					'AccountUserName',
					'EmailAddress',
					'LisSourcedId',
					'LtiContextId',
					'LtiDeploymentId',
					'LtiPlatformId',
					'LtiToolId',
					'LtiUserId',
					'OneRosterSourcedId',
					'Other',
					'SisSourcedId',
					'SystemId'
				]
			},
			User: {
				title: 'User',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'User',
						enum: ['User']
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					name: {
						type: 'string'
					},
					firstName: {
						type: 'string'
					},
					lastName: {
						type: 'string'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Status: {
				type: 'string',
				title: 'Status',
				enum: ['Inactive', 'Active']
			},
			Instructor: {
				title: 'Instructor',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Instructor',
						enum: ['Instructor']
					},
					permissions: {
						type: 'object',
						additionalProperties: true
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					name: {
						type: 'string'
					},
					firstName: {
						type: 'string'
					},
					lastName: {
						type: 'string'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Student: {
				title: 'Student',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Student',
						enum: ['Student']
					},
					gradeLevel: {
						type: 'number'
					},
					individualEducationPlan: {
						type: 'boolean'
					},
					englishLanguageLearner: {
						type: 'boolean'
					},
					settings: {
						type: 'object',
						additionalProperties: true,
						properties: {
							spanishLanguage: {
								type: 'array',
								items: {
									type: 'string'
								}
							},
							textToSpeech: {
								type: 'array',
								items: {
									type: 'string'
								}
							},
							languageTranslationTools: {
								type: 'array',
								items: {
									type: 'string'
								}
							}
						}
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					name: {
						type: 'string'
					},
					firstName: {
						type: 'string'
					},
					lastName: {
						type: 'string'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Group: {
				title: 'Group',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Group',
						enum: ['Group']
					},
					subOrganizationOf: {
						title: 'Organization',
						allOf: [
							{
								required: ['type', 'id']
							},
							{
								title: 'Organization',
								$ref: '#/definitions/Organization'
							}
						]
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Organization: {
				title: 'Organization',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Organization',
						enum: ['Organization']
					},
					subOrganizationOf: {
						title: 'Organization',
						allOf: [
							{
								required: ['type', 'id']
							},
							{
								title: 'Organization',
								$ref: '#/definitions/Organization'
							}
						]
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Class: {
				title: 'Class',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Class',
						enum: ['Class']
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					subOrganizationOf: {
						title: 'Organization',
						allOf: [
							{
								required: ['type', 'id']
							},
							{
								title: 'Organization',
								$ref: '#/definitions/Organization'
							}
						]
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			CaliperProfile: {
				type: 'string',
				title: 'CaliperProfile',
				enum: [
					'GeneralProfile',
					'AnnotationProfile',
					'AssessmentProfile',
					'AssignableProfile',
					'FeedbackProfile',
					'ForumProfile',
					'GradingProfile',
					'MediaProfile',
					'ReadingProfile',
					'ResourceManagementProfile',
					'SearchProfile',
					'SessionProfile',
					'ToolLaunchProfile',
					'ToolUseProfile'
				]
			},
			Entity: {
				title: 'Entity',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Entity',
						enum: ['Entity']
					},
					name: {
						type: 'string'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Membership: {
				title: 'Membership',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Membership',
						enum: ['Membership']
					},
					member: {
						required: ['id', 'type'],
						oneOf: [
							{
								title: 'Person',
								$ref: '#/definitions/Person'
							},
							{
								title: 'User',
								$ref: '#/definitions/User'
							},
							{
								title: 'Instructor',
								$ref: '#/definitions/Instructor'
							},
							{
								title: 'Student',
								$ref: '#/definitions/Student'
							}
						]
					},
					organization: {
						required: ['id', 'type'],
						oneOf: [
							{
								title: 'Organization',
								$ref: '#/definitions/Organization'
							},
							{
								title: 'School',
								$ref: '#/definitions/School'
							},
							{
								title: 'Group',
								$ref: '#/definitions/Group'
							},
							{
								title: 'Class',
								$ref: '#/definitions/Class'
							}
						]
					},
					roles: {
						type: 'array',
						items: {
							title: 'Role',
							$ref: '#/definitions/Role'
						}
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Person: {
				title: 'Person',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Person',
						enum: ['Person']
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			School: {
				title: 'School',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'School',
						enum: ['School']
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					subOrganizationOf: {
						title: 'Organization',
						allOf: [
							{
								required: ['type', 'id']
							},
							{
								title: 'Organization',
								$ref: '#/definitions/Organization'
							}
						]
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Role: {
				title: 'Role',
				type: 'string',
				enum: [
					'Learner',
					'Learner#Learner',
					'Learner#ExternalLearner',
					'Learner#GuestLearner',
					'Learner#NonCreditLearner',
					'Instructor',
					'Instructor#Instructor',
					'Instructor#Grader',
					'Instructor#ExternalInstructor',
					'Instructor#GuestInstructor',
					'Instructor#Lecturer',
					'Instructor#PrimaryInstructor',
					'Instructor#SecondaryInstructor',
					'Instructor#TeachingAssistant',
					'Instructor#TeachingAssistantGroup',
					'Instructor#TeachingAssistantSection',
					'Instructor#TeachingAssistantOffering',
					'Instructor#TeachingAssistantTemplate',
					'Administrator',
					'Administrator#Administrator',
					'Administrator#Developer',
					'Administrator#Support',
					'Administrator#SystemAdministrator',
					'Administrator#ExternalDeveloper',
					'Administrator#ExternalSupport',
					'Administrator#ExternalSystemAdministrator',
					'ContentDeveloper',
					'ContentDeveloper#ContentDeveloper',
					'ContentDeveloper#Librarian',
					'ContentDeveloper#ContentExpert',
					'ContentDeveloper#ExternalContentExpert',
					'Manager',
					'Manager#Manager',
					'Manager#AreaManager',
					'Manager#CourseCoordinator',
					'Manager#Observer',
					'Manager#ExternalObserver',
					'Member',
					'Member#Member',
					'Mentor',
					'Mentor#Mentor',
					'Mentor#Advisor',
					'Mentor#Auditor',
					'Mentor#Reviewer',
					'Mentor#Tutor',
					'Mentor#LearningFacilitator',
					'Mentor#ExternalMentor',
					'Mentor#ExternalAdvisor',
					'Mentor#ExternalAuditor',
					'Mentor#ExternalReviewer',
					'Mentor#ExternalTutor',
					'Mentor#ExternalLearningFacilitator',
					'Officer',
					'Officer#Officer',
					'Officer#Chair',
					'Officer#Secretary',
					'Officer#Treasurer',
					'Officer#Vice-Chair'
				]
			},
			LtiSession: {
				title: 'LtiSession',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'LtiSession',
						enum: ['LtiSession']
					},
					messageParameters: {
						type: 'object',
						additionalProperties: true
					},
					user: {
						required: ['id', 'type'],
						oneOf: [
							{
								title: 'Person',
								$ref: '#/definitions/Person'
							},
							{
								title: 'User',
								$ref: '#/definitions/User'
							},
							{
								title: 'Instructor',
								$ref: '#/definitions/Instructor'
							},
							{
								title: 'Student',
								$ref: '#/definitions/Student'
							}
						]
					},
					startedAtTime: {
						type: 'string',
						format: 'date-time'
					},
					endedAtTime: {
						type: 'string',
						format: 'date-time'
					},
					duration: {
						type: 'string',
						pattern: '^P(?:\\d+Y)?(?:\\d+M)?(?:\\d+D)?T?(?:\\d+H)?(?:\\d+M)?(?:\\d+S)?'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Session: {
				title: 'Session',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Session',
						enum: ['Session']
					},
					user: {
						required: ['id', 'type'],
						oneOf: [
							{
								title: 'Person',
								$ref: '#/definitions/Person'
							},
							{
								title: 'User',
								$ref: '#/definitions/User'
							},
							{
								title: 'Instructor',
								$ref: '#/definitions/Instructor'
							},
							{
								title: 'Student',
								$ref: '#/definitions/Student'
							}
						]
					},
					startedAtTime: {
						type: 'string',
						format: 'date-time'
					},
					endedAtTime: {
						type: 'string',
						format: 'date-time'
					},
					duration: {
						type: 'string',
						pattern: '^P(?:\\d+Y)?(?:\\d+M)?(?:\\d+D)?T?(?:\\d+H)?(?:\\d+M)?(?:\\d+S)?'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			}
		}
	}
};
