/** This file was Autogenerated */

import Caliper from './../Caliper';
import { IAgent } from './../Entities/Agent';
import { CredentialType } from './../Entities/CredentialType';
import { IDigitalResource } from './../Entities/DigitalResource';
import { IEntity } from './../Entities/Entity';
import { EntityType } from './../Entities/EntityType';
import { IInstructor } from './../Entities/Instructor';
import { LoginType } from './../Entities/LoginType';
import { ILtiSession } from './../Entities/LtiSession';
import { IMembership } from './../Entities/Membership';
import { IOrganization } from './../Entities/Organization';
import { IPerson } from './../Entities/Person';
import { ISession } from './../Entities/Session';
import { ISoftwareApplication } from './../Entities/SoftwareApplication';
import { IStudent } from './../Entities/Student';
import { IUser } from './../Entities/User';
import { ISystemIdentifier } from './../SystemIdentifier';
import { CaliperAction } from './CaliperAction';
import { CaliperProfile } from './CaliperProfile';
import { EventType } from './EventType';
import { ILoginEvent, ILoginEventUserSession } from './Internals/LoginEvent';

export interface ILoginFailedEvent extends ILoginEvent {
	actor: IUser | IInstructor | IStudent;
	object: ISoftwareApplication;
	session: ILoginFailedEventUserSession;
	target?: IDigitalResource;
	referrer?: IDigitalResource | ISoftwareApplication;
}

interface ILoginFailedEventParams {
	actor: IUser | IInstructor | IStudent;
	object: ISoftwareApplication;
	session: ILoginFailedEventUserSession;
	target?: IDigitalResource;
	referrer?: IDigitalResource | ISoftwareApplication;
	profile?: CaliperProfile;
	generated?: IEntity;
	group?: IOrganization;
	membership?: IMembership;
	federatedSession?: ILtiSession;
	extensions?: Record<string, any>;
}

export function LoginFailedEvent(params: ILoginFailedEventParams): ILoginFailedEvent {
	return {
		['@context']: ['http://edgenuity.com/events/login-failed/0-0-2', 'http://purl.imsglobal.org/ctx/caliper/v1p2'],
		action: CaliperAction.Declined,
		type: EventType.SessionEvent,
		id: Caliper.uuid(),
		eventTime: Caliper.timestamp(),
		edApp: Caliper.edApp(),
		...params
	};
}

export interface ILoginFailedEventUserSession extends ILoginEventUserSession {
	id: string;
	loginType: LoginType;
	credentials: CredentialType[];
	scopes: string[];
	userAgent: string;
	ipAddress: string;
	localTimestamp: string;
	description: string;
	user?: IPerson | IUser | IInstructor | IStudent;
}

interface ILoginFailedEventUserSessionParams {
	id: string;
	loginType: LoginType;
	credentials: CredentialType[];
	scopes: string[];
	userAgent: string;
	ipAddress: string;
	localTimestamp: string;
	description: string;
	user?: IPerson | IUser | IInstructor | IStudent;
	startedAtTime?: string;
	endedAtTime?: string;
	duration?: string;
	name?: string;
	dateCreated?: string;
	dateModified?: string;
	otherIdentifiers?: ISystemIdentifier[];
	extensions?: Record<string, any>;
}

export function LoginFailedEvent_UserSession(params: ILoginFailedEventUserSessionParams): ILoginFailedEventUserSession {
	return {
		type: EntityType.UserSession,
		...params
	};
}

export const LoginFailedEventSchema = {
	context: 'http://edgenuity.com/events/login-failed/0-0-2',
	schema: {
		title: 'LoginFailedEvent',
		type: 'object',
		required: ['@context', 'action', 'actor', 'session', 'object', 'type', 'id', 'eventTime', 'edApp'],
		properties: {
			'@context': {
				type: 'array',
				items: [
					{
						type: 'string',
						default: 'http://edgenuity.com/events/login-failed/0-0-2',
						enum: ['http://edgenuity.com/events/login-failed/0-0-2']
					},
					{
						type: 'string',
						default: 'http://purl.imsglobal.org/ctx/caliper/v1p2',
						enum: ['http://purl.imsglobal.org/ctx/caliper/v1p2']
					}
				]
			},
			action: {
				type: 'string',
				default: 'Declined',
				enum: ['Declined']
			},
			actor: {
				required: ['id', 'type'],
				oneOf: [
					{
						title: 'User',
						$ref: '#/definitions/User'
					},
					{
						title: 'Instructor',
						$ref: '#/definitions/Instructor'
					},
					{
						title: 'Student',
						$ref: '#/definitions/Student'
					}
				]
			},
			session: {
				title: 'UserSession',
				allOf: [
					{
						required: [
							'description',
							'loginType',
							'credentials',
							'scopes',
							'userAgent',
							'ipAddress',
							'localTimestamp',
							'type',
							'id'
						]
					},
					{
						title: 'UserSession',
						$ref: '#/definitions/UserSession'
					}
				]
			},
			object: {
				title: 'SoftwareApplication',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'SoftwareApplication',
						$ref: '#/definitions/SoftwareApplication'
					}
				]
			},
			type: {
				type: 'string',
				default: 'SessionEvent',
				enum: ['SessionEvent']
			},
			target: {
				title: 'DigitalResource',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'DigitalResource',
						$ref: '#/definitions/DigitalResource'
					}
				]
			},
			referrer: {
				required: ['id', 'type'],
				oneOf: [
					{
						title: 'DigitalResource',
						$ref: '#/definitions/DigitalResource'
					},
					{
						title: 'SoftwareApplication',
						$ref: '#/definitions/SoftwareApplication'
					}
				]
			},
			id: {
				type: 'string',
				pattern: 'urn\\:uuid\\:\\w{8}-\\w{4}-\\w{4}-\\w{4}-\\w{12}'
			},
			eventTime: {
				type: 'string',
				format: 'date-time'
			},
			edApp: {
				title: 'SoftwareApplication',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'SoftwareApplication',
						$ref: '#/definitions/SoftwareApplication'
					}
				]
			},
			profile: {
				title: 'CaliperProfile',
				$ref: '#/definitions/CaliperProfile'
			},
			generated: {
				title: 'Entity',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'Entity',
						$ref: '#/definitions/Entity'
					}
				]
			},
			group: {
				title: 'Organization',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'Organization',
						$ref: '#/definitions/Organization'
					}
				]
			},
			membership: {
				title: 'Membership',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'Membership',
						$ref: '#/definitions/Membership'
					}
				]
			},
			federatedSession: {
				title: 'LtiSession',
				allOf: [
					{
						required: ['type', 'id']
					},
					{
						title: 'LtiSession',
						$ref: '#/definitions/LtiSession'
					}
				]
			},
			extensions: {
				type: 'object',
				additionalProperties: true
			}
		},
		definitions: {
			User: {
				title: 'User',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'User',
						enum: ['User']
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					name: {
						type: 'string'
					},
					firstName: {
						type: 'string'
					},
					lastName: {
						type: 'string'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Status: {
				type: 'string',
				title: 'Status',
				enum: ['Inactive', 'Active']
			},
			Uri: {
				type: 'string',
				oneOf: [
					{
						pattern: '^https?:\\/\\/\\w.+\\.\\w+[/\\w+]*'
					},
					{
						pattern: 'urn\\:.*'
					}
				]
			},
			SystemIdentifier: {
				title: 'SystemIdentifier',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'SystemIdentifier',
						enum: ['SystemIdentifier']
					},
					identifierType: {
						title: 'SystemIdentifierType',
						$ref: '#/definitions/SystemIdentifierType'
					},
					identifier: {
						type: 'string'
					},
					source: {
						title: 'SoftwareApplication',
						allOf: [
							{
								required: ['type', 'id']
							},
							{
								title: 'SoftwareApplication',
								$ref: '#/definitions/SoftwareApplication'
							}
						]
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			SystemIdentifierType: {
				type: 'string',
				title: 'SystemIdentifierType',
				enum: [
					'AccountUserName',
					'EmailAddress',
					'LisSourcedId',
					'LtiContextId',
					'LtiDeploymentId',
					'LtiPlatformId',
					'LtiToolId',
					'LtiUserId',
					'OneRosterSourcedId',
					'Other',
					'SisSourcedId',
					'SystemId'
				]
			},
			SoftwareApplication: {
				title: 'SoftwareApplication',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'SoftwareApplication',
						enum: ['SoftwareApplication']
					},
					version: {
						type: 'string'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Instructor: {
				title: 'Instructor',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Instructor',
						enum: ['Instructor']
					},
					permissions: {
						type: 'object',
						additionalProperties: true
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					name: {
						type: 'string'
					},
					firstName: {
						type: 'string'
					},
					lastName: {
						type: 'string'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Student: {
				title: 'Student',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Student',
						enum: ['Student']
					},
					gradeLevel: {
						type: 'number'
					},
					individualEducationPlan: {
						type: 'boolean'
					},
					englishLanguageLearner: {
						type: 'boolean'
					},
					settings: {
						type: 'object',
						additionalProperties: true,
						properties: {
							spanishLanguage: {
								type: 'array',
								items: {
									type: 'string'
								}
							},
							textToSpeech: {
								type: 'array',
								items: {
									type: 'string'
								}
							},
							languageTranslationTools: {
								type: 'array',
								items: {
									type: 'string'
								}
							}
						}
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					name: {
						type: 'string'
					},
					firstName: {
						type: 'string'
					},
					lastName: {
						type: 'string'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			UserSession: {
				title: 'UserSession',
				type: 'object',
				properties: {
					description: {
						type: 'string'
					},
					loginType: {
						title: 'LoginType',
						$ref: '#/definitions/LoginType'
					},
					credentials: {
						type: 'array',
						items: {
							title: 'CredentialType',
							$ref: '#/definitions/CredentialType'
						}
					},
					scopes: {
						type: 'array',
						items: {
							type: 'string'
						}
					},
					userAgent: {
						type: 'string'
					},
					ipAddress: {
						title: 'IPAddress',
						$ref: '#/definitions/IPAddress'
					},
					localTimestamp: {
						type: 'string',
						pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?[-|\\+]\\d{2}:\\d{2}'
					},
					type: {
						type: 'string',
						default: 'UserSession',
						enum: ['UserSession']
					},
					user: {
						required: ['id', 'type'],
						oneOf: [
							{
								title: 'Person',
								$ref: '#/definitions/Person'
							},
							{
								title: 'User',
								$ref: '#/definitions/User'
							},
							{
								title: 'Instructor',
								$ref: '#/definitions/Instructor'
							},
							{
								title: 'Student',
								$ref: '#/definitions/Student'
							}
						]
					},
					startedAtTime: {
						type: 'string',
						format: 'date-time'
					},
					endedAtTime: {
						type: 'string',
						format: 'date-time'
					},
					duration: {
						type: 'string',
						pattern: '^P(?:\\d+Y)?(?:\\d+M)?(?:\\d+D)?T?(?:\\d+H)?(?:\\d+M)?(?:\\d+S)?'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			LoginType: {
				type: 'string',
				title: 'LoginType',
				enum: ['QRCodeSwipeFromALA', 'SAML', 'CleverApi', 'LtiSSO', 'GoogleAuthentication', 'ApplicationLoginPage']
			},
			CredentialType: {
				type: 'string',
				title: 'CredentialType',
				enum: ['Username', 'Password', 'QRCode']
			},
			IPAddress: {
				type: 'string',
				oneOf: [
					{
						pattern: '^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$'
					},
					{
						pattern: '^\\w{1,4}(:\\w{1,4}){7}$'
					}
				]
			},
			Person: {
				title: 'Person',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Person',
						enum: ['Person']
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			DigitalResource: {
				title: 'DigitalResource',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'DigitalResource',
						enum: ['DigitalResource']
					},
					learningObjectives: {
						type: 'array',
						items: {
							title: 'LearningObjective',
							allOf: [
								{
									required: ['type', 'id']
								},
								{
									title: 'LearningObjective',
									$ref: '#/definitions/LearningObjective'
								}
							]
						}
					},
					keywords: {
						type: 'array',
						items: {
							type: 'string'
						}
					},
					creators: {
						type: 'array',
						items: {
							title: 'Agent',
							allOf: [
								{
									required: ['type', 'id']
								},
								{
									title: 'Agent',
									$ref: '#/definitions/Agent'
								}
							]
						}
					},
					mediaType: {
						type: 'string'
					},
					isPartOf: {
						title: 'Entity',
						allOf: [
							{
								required: ['type', 'id']
							},
							{
								title: 'Entity',
								$ref: '#/definitions/Entity'
							}
						]
					},
					datePublished: {
						type: 'string',
						format: 'date-time'
					},
					version: {
						type: 'string'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			LearningObjective: {
				title: 'LearningObjective',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'LearningObjective',
						enum: ['LearningObjective']
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Agent: {
				title: 'Agent',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Agent',
						enum: ['Agent']
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Entity: {
				title: 'Entity',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Entity',
						enum: ['Entity']
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			CaliperProfile: {
				type: 'string',
				title: 'CaliperProfile',
				enum: [
					'GeneralProfile',
					'AnnotationProfile',
					'AssessmentProfile',
					'AssignableProfile',
					'FeedbackProfile',
					'ForumProfile',
					'GradingProfile',
					'MediaProfile',
					'ReadingProfile',
					'ResourceManagementProfile',
					'SearchProfile',
					'SessionProfile',
					'ToolLaunchProfile',
					'ToolUseProfile'
				]
			},
			Organization: {
				title: 'Organization',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Organization',
						enum: ['Organization']
					},
					subOrganizationOf: {
						title: 'Organization',
						allOf: [
							{
								required: ['type', 'id']
							},
							{
								title: 'Organization',
								$ref: '#/definitions/Organization'
							}
						]
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Membership: {
				title: 'Membership',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Membership',
						enum: ['Membership']
					},
					member: {
						required: ['id', 'type'],
						oneOf: [
							{
								title: 'Person',
								$ref: '#/definitions/Person'
							},
							{
								title: 'User',
								$ref: '#/definitions/User'
							},
							{
								title: 'Instructor',
								$ref: '#/definitions/Instructor'
							},
							{
								title: 'Student',
								$ref: '#/definitions/Student'
							}
						]
					},
					organization: {
						required: ['id', 'type'],
						oneOf: [
							{
								title: 'Organization',
								$ref: '#/definitions/Organization'
							},
							{
								title: 'School',
								$ref: '#/definitions/School'
							},
							{
								title: 'Group',
								$ref: '#/definitions/Group'
							},
							{
								title: 'Class',
								$ref: '#/definitions/Class'
							}
						]
					},
					roles: {
						type: 'array',
						items: {
							title: 'Role',
							$ref: '#/definitions/Role'
						}
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			School: {
				title: 'School',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'School',
						enum: ['School']
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					subOrganizationOf: {
						title: 'Organization',
						allOf: [
							{
								required: ['type', 'id']
							},
							{
								title: 'Organization',
								$ref: '#/definitions/Organization'
							}
						]
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Group: {
				title: 'Group',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Group',
						enum: ['Group']
					},
					subOrganizationOf: {
						title: 'Organization',
						allOf: [
							{
								required: ['type', 'id']
							},
							{
								title: 'Organization',
								$ref: '#/definitions/Organization'
							}
						]
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Class: {
				title: 'Class',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'Class',
						enum: ['Class']
					},
					status: {
						title: 'Status',
						$ref: '#/definitions/Status'
					},
					subOrganizationOf: {
						title: 'Organization',
						allOf: [
							{
								required: ['type', 'id']
							},
							{
								title: 'Organization',
								$ref: '#/definitions/Organization'
							}
						]
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			},
			Role: {
				title: 'Role',
				type: 'string',
				enum: [
					'Learner',
					'Learner#Learner',
					'Learner#ExternalLearner',
					'Learner#GuestLearner',
					'Learner#NonCreditLearner',
					'Instructor',
					'Instructor#Instructor',
					'Instructor#Grader',
					'Instructor#ExternalInstructor',
					'Instructor#GuestInstructor',
					'Instructor#Lecturer',
					'Instructor#PrimaryInstructor',
					'Instructor#SecondaryInstructor',
					'Instructor#TeachingAssistant',
					'Instructor#TeachingAssistantGroup',
					'Instructor#TeachingAssistantSection',
					'Instructor#TeachingAssistantOffering',
					'Instructor#TeachingAssistantTemplate',
					'Administrator',
					'Administrator#Administrator',
					'Administrator#Developer',
					'Administrator#Support',
					'Administrator#SystemAdministrator',
					'Administrator#ExternalDeveloper',
					'Administrator#ExternalSupport',
					'Administrator#ExternalSystemAdministrator',
					'ContentDeveloper',
					'ContentDeveloper#ContentDeveloper',
					'ContentDeveloper#Librarian',
					'ContentDeveloper#ContentExpert',
					'ContentDeveloper#ExternalContentExpert',
					'Manager',
					'Manager#Manager',
					'Manager#AreaManager',
					'Manager#CourseCoordinator',
					'Manager#Observer',
					'Manager#ExternalObserver',
					'Member',
					'Member#Member',
					'Mentor',
					'Mentor#Mentor',
					'Mentor#Advisor',
					'Mentor#Auditor',
					'Mentor#Reviewer',
					'Mentor#Tutor',
					'Mentor#LearningFacilitator',
					'Mentor#ExternalMentor',
					'Mentor#ExternalAdvisor',
					'Mentor#ExternalAuditor',
					'Mentor#ExternalReviewer',
					'Mentor#ExternalTutor',
					'Mentor#ExternalLearningFacilitator',
					'Officer',
					'Officer#Officer',
					'Officer#Chair',
					'Officer#Secretary',
					'Officer#Treasurer',
					'Officer#Vice-Chair'
				]
			},
			LtiSession: {
				title: 'LtiSession',
				type: 'object',
				properties: {
					type: {
						type: 'string',
						default: 'LtiSession',
						enum: ['LtiSession']
					},
					messageParameters: {
						type: 'object',
						additionalProperties: true
					},
					user: {
						required: ['id', 'type'],
						oneOf: [
							{
								title: 'Person',
								$ref: '#/definitions/Person'
							},
							{
								title: 'User',
								$ref: '#/definitions/User'
							},
							{
								title: 'Instructor',
								$ref: '#/definitions/Instructor'
							},
							{
								title: 'Student',
								$ref: '#/definitions/Student'
							}
						]
					},
					startedAtTime: {
						type: 'string',
						format: 'date-time'
					},
					endedAtTime: {
						type: 'string',
						format: 'date-time'
					},
					duration: {
						type: 'string',
						pattern: '^P(?:\\d+Y)?(?:\\d+M)?(?:\\d+D)?T?(?:\\d+H)?(?:\\d+M)?(?:\\d+S)?'
					},
					id: {
						title: 'Uri',
						$ref: '#/definitions/Uri'
					},
					name: {
						type: 'string'
					},
					description: {
						type: 'string'
					},
					dateCreated: {
						type: 'string',
						format: 'date-time'
					},
					dateModified: {
						type: 'string',
						format: 'date-time'
					},
					otherIdentifiers: {
						type: 'array',
						items: {
							title: 'SystemIdentifier',
							allOf: [
								{
									required: ['type', 'identifierType', 'identifier', 'source']
								},
								{
									title: 'SystemIdentifier',
									$ref: '#/definitions/SystemIdentifier'
								}
							]
						}
					},
					extensions: {
						type: 'object',
						additionalProperties: true
					}
				}
			}
		}
	}
};
