/** This file was Autogenerated */

import { ISystemIdentifier } from '../SystemIdentifier';
import { IDigitalResource } from './DigitalResource';
import { IEntity } from './Entity';
import { EntityType } from './EntityType';

export interface IAssignableDigitalResource extends IDigitalResource {
	id: string;
	dateToActivate?: string;
	dateToShow?: string;
	dateToStartOn?: string;
	dateToSubmit?: string;
	maxAttempts?: number;
	maxSubmits?: number;
	maxScore?: number;
}

export interface IAssignableDigitalResourceParams {
	id: string;
	dateToActivate?: string;
	dateToShow?: string;
	dateToStartOn?: string;
	dateToSubmit?: string;
	maxAttempts?: number;
	maxSubmits?: number;
	maxScore?: number;
	mediaType?: string;
	isPartOf?: IEntity;
	datePublished?: string;
	version?: string;
	name?: string;
	description?: string;
	dateCreated?: string;
	dateModified?: string;
	otherIdentifiers?: ISystemIdentifier[];
	extensions?: Record<string, any>;
}

export function AssignableDigitalResource(
	params: IAssignableDigitalResourceParams
): IAssignableDigitalResource {
	return {
		type: EntityType.AssignableDigitalResource,
		learningObjectives: [],
		keywords: [],
		creators: [],
		...params,
	};
}
