/** This file was Autogenerated */
export enum LoginType {
	QRCodeSwipeFromALA = 'QRCodeSwipeFromALA',
	SAML = 'SAML',
	CleverApi = 'CleverApi',
	LtiSSO = 'LtiSSO',
	GoogleAuthentication = 'GoogleAuthentication',
	ApplicationLoginPage = 'ApplicationLoginPage',
}
