/** This file was Autogenerated */

import Caliper from './../Caliper';

export interface StudentProfileSettings {
	spanishLanguage?: string[];
	textToSpeech?: string[];
	languageTranslationTools?: string[];
	[key: string]: any;
}
